version: "3.3"

services:
  db:
    image: mariadb:10.1.44
    restart: on-failure
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: example
      MYSQL_USER: user
      MYSQL_PASSWORD:
    volumes:
      - ./data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    environment:
      APP_ENV: ${APP_ENV}
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
    volumes:
      - .:/usr/src/
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
    working_dir: /usr/src

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - ./public/:/usr/src/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  # Utils
  adminer:
    image: adminer
    restart: on-failure

  node:
    image: node:10
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    user:
